booking_id=int(input("Enter Booking ID: "))
customer_name=input("Enter Customer Name: ")
ticket_cost=float(input("Enter Ticket Cost: "))
booking_channel=input("Enter Booking Channel (Online/Box Office): ")
available_seats=int(input("Enter Number of Available Seats: "))
booked_seats=int(input("Enter Number of Booked Seats: "))
student_discount=float(input("Enter Discount for Students (%): "))
movie_type=input("Enter Movie Type (2D/3D/IMAX): ")
theatre_name=input("Enter Theatre Name: ")
support_contact=input("Enter Support Contact Number: ")
theatre_location=input("Enter Theatre Location: ")
print("\n--- Booking Summary ---")
print(f"Booking ID:{booking_id}")
print(f"Customer Name:{customer_name}")
print(f"Ticket Cost:{ticket_cost}")
print(f"Booking Channel:{booking_channel}")
print(f"Available Seats:{available_seats}")
print(f"Booked Seats:{booked_seats}")
print(f"Student Discount:{student_discount}%")
print(f"Movie Type:{movie_type}")
print(f"Theatre:{theatre_name},Contact:{support_contact},Location:{theatre_location}")